### ISSUE TITLE
can: request_module (can-proto-6) failed for CAN_ISOTP.

### ISSUE THREAD

**Issue by miteshdube** [OpenNuvoton/NUC980_Linux_Applications#2]
I am trying to implement CAN_ISOTP. I have replaced the CAN_RAW with CAN_ISOTP in provided [example](https://github.com/OpenNuvoton/NUC980_Linux_Applications/blob/master/demos/CAN/can.c)

`int family = PF_CAN, type = SOCK_RAW, proto = CAN_RAW;`
Replaced above line with,
`int family = PF_CAN, type = SOCK_RAW, proto = CAN_ISOTP;`

After executing this, it's output is as below,
`can: request_module (can-proto-6) failed.`

Also tried with `isotpsend` and `isotprecv` same error I'm getting.
Device 1 (Sender):-
```
~ # echo 11 22 33 44 55 66 DE AD BE EF | isotpsend -s 321 -d 123 can0
can: request_module (can-proto-6) failed.
socket: Protocol not supported
```
Device 2 (Receiver):-
```
~ # isotprecv -s 123 -d 321 -l can0
can: request_module (can-proto-6) failed.
socket: Protocol not supported
```

As it is showing socket is not supporting protocol then, how I can add support for the ISOTP protocol.

**Comment by yachen** [comment]
Did you install the can-isotp.ko?
https://github.com/hartkopp/can-isotp

**Comment by miteshdube** [comment]
No I did not installed can-isotp.ko module. Do you have any reference to build this kernel module for NUC980?

**Comment by miteshdube** [comment]
I'm getting the error while installing the module.
```
~ # insmod /lib/modules/4.4.207/kernel/can-isotp.ko 
insmod: can't insert '/lib/modules/4.4.207/kernel/can-isotp.ko': invalid module format

```

**Comment by yachen** [comment]
What's the output of "file can-isotp.ko" on your Linux PC?

**Comment by miteshdube** [comment]
Output of `make`:
```
$ make
make -C /lib/modules/4.15.0-154-generic/build M=/home/mitesh/GMG/can-isotp modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-154-generic'
  CC [M]  /home/mitesh/GMG/can-isotp/net/can/isotp.o
/home/mitesh/GMG/can-isotp/net/can/isotp.c:1541:12: warning: ‘isotp_sock_no_ioctlcmd’ defined but not used [-Wunused-function]
 static int isotp_sock_no_ioctlcmd(struct socket *sock, unsigned int cmd,
            ^~~~~~~~~~~~~~~~~~~~~~
  LD [M]  /home/mitesh/GMG/can-isotp/net/can/can-isotp.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/mitesh/GMG/can-isotp/net/can/can-isotp.mod.o
  LD [M]  /home/mitesh/GMG/can-isotp/net/can/can-isotp.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-154-generic'

```
Output of `sudo make modules_install` :
 ```
$ sudo make modules_install 
make -C /lib/modules/4.15.0-154-generic/build M=/home/mitesh/GMG/can-isotp modules_install
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-154-generic'
  INSTALL /home/mitesh/GMG/can-isotp/net/can/can-isotp.ko
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:72
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:79
sign-file: certs/signing_key.pem: No such file or directory
  DEPMOD  4.15.0-154-generic
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-154-generic'
```
Output of `sudo insmod ./net/can/can-isotp.ko`:
```
$ sudo insmod ./net/can/can-isotp.ko
insmod: ERROR: could not insert module ./net/can/can-isotp.ko: Unknown symbol in module

```

This is the output on my PC(Ubuntu18.04).

**Comment by yachen** [comment]
Please provide the output of following command on your Ubuntu PC, not build procedure. Thanks.
```
file can-isotp.ko
```

**Comment by miteshdube** [comment]
Thank you for considering my mistake. Here is the output of `file can-iso.ko`:

```
$ file can-isotp.ko 
can-isotp.ko: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), BuildID[sha1]=76f8fd462dc8c4e41e719a503def28e6b847294c, not stripped

```

**Comment by yachen** [comment]
You should include NUC980's Linux header and cross compile this module for ARM9 instead of your host machine (x86-64).

**Comment by miteshdube** [comment]
Thank you but I'm new to cross compiling kernel modules.Could you please provide source of NUC980's Linux header and cross compile tool for ARM9 and reference procedure for the same?

**Comment by yachen** [comment]
You can build and install cross compile tool chain from buildroot here. Buildroot will also install the kernel header.
https://github.com/OpenNuvoton/NUC970_Buildroot
Or you can download kernel source from here:
https://github.com/OpenNuvoton/NUC980-linux-4.4.y

**Comment by miteshdube** [comment]
Issue solved. Thank you for your kind support.

**Comment by tarek857** [comment]
@miteshdube hi 
installing of can-isotp.ko solved the issue for you ?

**Comment by miteshdube** [comment]
> @miteshdube hi installing of can-isotp.ko solved the issue for you ?

@tarek857 Yes.

**Comment by Abhidube07** [comment]
@miteshdube 

Hello Mitesh,

I am getting this same issue. Can you please give detail over view how you performed "You should include NUC980's Linux header and cross compile this module for ARM9" this step. I am not getting how to include kernel header. Thanks in advance.

**Comment by mjchen1** [comment]
Hi Abhidube07,
You can try compiling with buildroot:
1. git clone https://github.com/OpenNuvoton/NUC970_Buildroot.git
2. make nuvoton_nuc980_defconfig (or other nuvoton_nuc980_xxx_defconfig)
3. use "make linux-menuconfig" to set kernel config
4. make
