### ISSUE TITLE
how to build openssl with H/W acceleration on nuc980?

### ISSUE THREAD

**Issue by qinxin0720** [OpenNuvoton/NUC980_Linux_Applications#3]

**Comment by ychuang3** [comment]
Hi,

Try this

/* Create the destination folder ”openssl” */
#  mkdir /linux/arm-source/openssl
/* Go to the open source folder */
# cd NUC970_Buildroot-master/nuc980bsp/application/openssl-1.1.1/
/* Generate Makefile */
# ./Configure linux-generic32 no-asm shared no-async --prefix=/home/user/linux/arm-source/openssl CROSS_COMPILE=arm-linux- CC=gcc
/* Compile and generate executable file */
#make
#make install

/* Check the destination folder */
# cd linux/arm-source/openssl/
#ls

/* Copy “openssl” folder  to “ /NUC970_Buildroot-master/output/target/opt” */
# cp –r /home/user/linux/arm-source/openssl   /home/user/ NUC970_Buildroot-master/output/target/opt


/* Compile and download Image to target board */
On the board side:
Modify the environment variable
# export LD_LIBRARY_PATH=/opt/openssl/lib:$LD_LIBRARY_PATH

/* Start the openssl */
# ./opt/openssl/bin/openssl
 
/* Test */
# ./opt/openssl/bin/openssl speed rsa2048

Jacky

**Comment by qinxin0720** [comment]
Thanks a lot!
